# Generated by Django 2.0 on 2019-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_auto_20190801_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='static/images/shop/product9.jpg', upload_to='static/images/products', verbose_name='My Photo'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
