# Generated by Django 2.0 on 2019-08-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_auto_20190801_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='static/images/products'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
