# Generated by Django 2.0 on 2019-08-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_auto_20190808_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
